version: "3.5"
services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-boot-admin
    labels:
      - com.github.joostvdg.namespace=appregister
      - com.github.joostvdg.name="Spring Boot Admin"
      - com.github.joostvdg.description="Admin console for spring boot applications"
      - com.github.joostvdg.webPath=/
      - com.github.joostvdg.webPort=8888
    ports:
      - 8888:8080

  consul:
    image: consul
    labels:
      - com.github.joostvdg.namespace=appregister
      - com.github.joostvdg.name="Consul"
      - com.github.joostvdg.description="Config and Discovery server"
    ports:
      - 8500:8500